import cv2
#image= cv2.imread("Taj.png")
image= cv2.imread("coins02.png")
r = 100/image.shape[1]
dim = (100, int(image.shape[0] * r))
image_resized = cv2.resize(image, dim, interpolation =cv2.INTER_AREA)
cv2.imshow("image_resized", image_resized)
cv2.waitKey(0)
grayimage = cv2.cvtColor(image_resized, cv2.COLOR_BGR2GRAY)
cv2.imshow("grayscale image", grayimage)
cv2.waitKey(0)
gblurimmage = cv2.GaussianBlur(grayimage, (7, 7), 20)
cv2.imshow("blurred image", gblurimmage)
cv2.waitKey(0)
thresh = cv2.adaptiveThreshold(gblurimmage, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY_INV, 25, 25)
cv2.imshow("thresholded image", thresh)
cv2.waitKey(0)
cv2.imshow("Output", cv2.bitwise_and(image_resized, image_resized, mask=thresh))
cv2.waitKey(0)